//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDashboard
{
    public partial class index
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
        protected global::System.Web.UI.WebControls.Label lblTotalProfit;
        protected global::System.Web.UI.WebControls.Label lblProductCount;
        protected global::System.Web.UI.WebControls.Label lblCustomerCount;
        protected global::System.Web.UI.WebControls.Label lblEmployeeCount;
        protected global::System.Web.UI.WebControls.Label lblLowStock;
        protected global::System.Web.UI.WebControls.GridView gvSales;
        protected global::System.Web.UI.WebControls.GridView gvProducts;
        protected global::System.Web.UI.WebControls.GridView gvCustomers;
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
        protected global::System.Web.UI.WebControls.HiddenField hfChartData;
    }
}
