//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDashboardWebForms
{
    public partial class index
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litExcelFile;
        protected global::System.Web.UI.WebControls.Literal litLoadedAt;
        protected global::System.Web.UI.WebControls.Button btnRefresh;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;
        protected global::System.Web.UI.WebControls.Literal litTotalProfit;
        protected global::System.Web.UI.WebControls.Literal litProductCount;
        protected global::System.Web.UI.WebControls.Literal litTotalStock;
        protected global::System.Web.UI.WebControls.Literal litCustomerCount;
        protected global::System.Web.UI.WebControls.Literal litMemberCount;
        protected global::System.Web.UI.WebControls.Literal litEmployeeCount;
        protected global::System.Web.UI.WebControls.Literal litSaleCount;
        protected global::System.Web.UI.WebControls.Literal litAvgOrder;
        protected global::System.Web.UI.WebControls.Literal litTopProduct;
        protected global::System.Web.UI.WebControls.Literal litTopCustomer;
        protected global::System.Web.UI.WebControls.GridView gvCategories;
        protected global::System.Web.UI.WebControls.GridView gvProducts;
        protected global::System.Web.UI.WebControls.GridView gvCustomers;
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
        protected global::System.Web.UI.WebControls.GridView gvSales;
        protected global::System.Web.UI.WebControls.HiddenField hfSalesDateLabels;
        protected global::System.Web.UI.WebControls.HiddenField hfSalesDateValues;
        protected global::System.Web.UI.WebControls.HiddenField hfSalesProductLabels;
        protected global::System.Web.UI.WebControls.HiddenField hfSalesProductValues;
        protected global::System.Web.UI.WebControls.HiddenField hfCategoryLabels;
        protected global::System.Web.UI.WebControls.HiddenField hfCategoryValues;
    }
}
