//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardWebApp
{
    public partial class index
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlDashboard;
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
        protected global::System.Web.UI.WebControls.Label lblTotalProducts;
        protected global::System.Web.UI.WebControls.Label lblTotalCustomers;
        protected global::System.Web.UI.WebControls.Label lblTotalEmployees;
        protected global::System.Web.UI.WebControls.Label lblTotalSales;
        protected global::System.Web.UI.WebControls.Label lblStockValue;
        protected global::System.Web.UI.WebControls.GridView gvSales;
        protected global::System.Web.UI.WebControls.Repeater rptCategories;
        protected global::System.Web.UI.WebControls.GridView gvProducts;
        protected global::System.Web.UI.WebControls.GridView gvCustomers;
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
    }
}
