//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tset
{
    public partial class index
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litLastUpdate;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;
        protected global::System.Web.UI.WebControls.Literal litTotalSales;
        protected global::System.Web.UI.WebControls.Literal litTotalProducts;
        protected global::System.Web.UI.WebControls.Literal litLowStock;
        protected global::System.Web.UI.WebControls.Literal litTotalCustomers;
        protected global::System.Web.UI.WebControls.Literal litMemberCount;
        protected global::System.Web.UI.WebControls.Literal litTotalEmployees;
        protected global::System.Web.UI.WebControls.Literal litTotalProfit;
        protected global::System.Web.UI.WebControls.GridView gvSales;
        protected global::System.Web.UI.WebControls.GridView gvProducts;
        protected global::System.Web.UI.WebControls.GridView gvCustomers;
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
        protected global::System.Web.UI.WebControls.HiddenField hfMonthlyLabels;
        protected global::System.Web.UI.WebControls.HiddenField hfMonthlyValues;
        protected global::System.Web.UI.WebControls.HiddenField hfCategoryLabels;
        protected global::System.Web.UI.WebControls.HiddenField hfCategoryValues;
    }
}
